config/routes.rb
Rails.application.routes.draw do
  
  resources :vote_schedules
  get 'home/index'
  get 'home/activate_selector'
  get 'home/candidate'
  get 'home/final_candidate'
  get 'home/select_candidate'
  get 'home/winner'

  resources :candidates do
    collection do
      get 'final_candidate'
    end
  end
  devise_for :users
  root to: "home#index"

end

app/models/vote_schedule.rb
class VoteSchedule < ActiveRecord::Base
  after_save :send_mail_to_voter

  def send_mail_to_voter
    voters = User.voter
    voters.each do |voter|
      final_candidate = Candidate.final_candidate
      AppMailer.voter(final_candidate,voter,vote_schedule = self).deliver
    end
  end
end

app/controllers/vote_schedules_controller.rb
class VoteSchedulesController < ApplicationController
  before_action :set_vote_schedule, only: [:show, :edit, :update, :destroy]

  # GET /vote_schedules
  # GET /vote_schedules.json
  def index
    @vote_schedules = VoteSchedule.all
  end

  # GET /vote_schedules/1
  # GET /vote_schedules/1.json
  def show
  end

  # GET /vote_schedules/new
  def new
    @vote_schedule = VoteSchedule.new
  end

  # GET /vote_schedules/1/edit
  def edit
  end

  # POST /vote_schedules
  # POST /vote_schedules.json
  def create
    @vote_schedule = VoteSchedule.new(vote_schedule_params)

    respond_to do |format|
      if @vote_schedule.save
        format.html { redirect_to @vote_schedule, notice: 'Vote schedule was successfully created.' }
        format.json { render :show, status: :created, location: @vote_schedule }
      else
        format.html { render :new }
        format.json { render json: @vote_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vote_schedules/1
  # PATCH/PUT /vote_schedules/1.json
  def update
    respond_to do |format|
      if @vote_schedule.update(vote_schedule_params)
        format.html { redirect_to @vote_schedule, notice: 'Vote schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote_schedule }
      else
        format.html { render :edit }
        format.json { render json: @vote_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vote_schedules/1
  # DELETE /vote_schedules/1.json
  def destroy
    @vote_schedule.destroy
    respond_to do |format|
      format.html { redirect_to vote_schedules_url, notice: 'Vote schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote_schedule
      @vote_schedule = VoteSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_schedule_params
      params.require(:vote_schedule).permit(:date_from, :date_to, :winner)
    end
end

app/helpers/vote_schedules_helper.rb
module VoteSchedulesHelper
end

app/views/vote_schedules/_form.html.erb
<%= form_for(@vote_schedule) do |f| %>
  <% if @vote_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote_schedule.errors.count, "error") %> prohibited this vote_schedule from being saved:</h2>

      <ul>
      <% @vote_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_from %><br>
    <%= f.datetime_select :date_from %>
  </div>
  <div class="field">
    <%= f.label :date_to %><br>
    <%= f.datetime_select :date_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vote_schedules/edit.html.erb
<h1>Editing Vote Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote_schedule %> |
<%= link_to 'Back', vote_schedules_path %>

app/views/vote_schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vote Schedules</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Date from</th>
      <th>Date to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vote_schedules.each do |vote_schedule| %>
      <tr>
        <td><%= vote_schedule.date_from %></td>
        <td><%= vote_schedule.date_to %></td>
        <td><%= link_to 'Show', vote_schedule %></td>
        <td><%= link_to 'Edit', edit_vote_schedule_path(vote_schedule) %></td>
        <td><%= link_to 'Destroy', vote_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote schedule', new_vote_schedule_path %>

app/views/vote_schedules/new.html.erb
<h1>New Vote Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', vote_schedules_path %>

app/views/vote_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date from:</strong>
  <%= @vote_schedule.date_from %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @vote_schedule.date_to %>
</p>


<%= link_to 'Edit', edit_vote_schedule_path(@vote_schedule) %> |
<%= link_to 'Back', vote_schedules_path %>