config/routes.rb
Rails.application.routes.draw do
  
  resources :vote_schedules
  get 'home/index'
  get 'home/activate_selector'
  get 'home/candidate'
  get 'home/final_candidate'
  get 'home/select_candidate'
  get 'home/winner'

  resources :candidates do
    collection do
      get 'final_candidate'
    end
  end
  devise_for :users
  root to: "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.role == 'Admin'
  	  @users = User.selector
     elsif current_user.role == 'Selector'  
       redirect_to home_candidate_url and return
     elsif current_user.role == 'Voter'
       redirect_to home_final_candidate_url and return   
  	 end
  end

  def select_candidate
  	current_user.candidate = Candidate.find(params[:id])
    redirect_to home_index_url and return
  end

  def final_candidate
    @candidate = Candidate.final_candidate
  end

  def winner
    Vote.winner
    @candidate = Candidate.find_by_winner(true)

  end

  def candidate
  	@candidates = Candidate.all
  end
  
  def activate_selector
    @user = User.find(params[:id])
    @user.activate_selector
    redirect_to home_index_url and return
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/candidate.html.erb
<% if current_user.candidate.present? %>
  <h3> Selected Candidate </h3>
  <h4>Candidate</h4>
  Name = <b><%= current_user.candidate.name %></b></br>
  Age = <b><%= current_user.candidate.age %></b>
<% else %>
<h1>Choose Candidate</h1>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Select Candidate</th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.age %></td>
        <td><%= link_to 'Select', home_select_candidate_path(:id => candidate.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/home/final_candidate.html.erb
<% if DateTime.now.between?(VoteSchedule.last.date_from , VoteSchedule.last.date_to) %>
  <% if current_user.candidate.present? %>
  <p> Selected Candidate</p>
    Name <%= current_user.candidate.name %></br>
    Age <%= current_user.candidate.age %>
  <% else%>
  <h1>Choose Candidates</h1>

  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Vote</th>
      </tr>
    </thead>

    <tbody>
      <% @candidates.each do |candidate| %>
        <tr>
          <td><%= candidate.name %></td>
          <td><%= candidate.age %></td>
         <td><%= link_to 'Select', home_select_candidate_path(:id => candidate.id)%></td>   
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
<% else %>
  <p>Voting Window open between <%= VoteSchedule.last.date_from %> to <%= VoteSchedule.last.date_to%>
<% end %>

app/views/home/index.html.erb
<%= javascript_include_tag "home.js" %>

<h1>Listing Selectors</h1>


<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Email</th>
      <th>Status</th>
      <th>Activate Selector</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.approved? ? 'Active' : 'Waiting For Approval' %></td>
        <td><%= link_to "Activate", home_activate_selector_path(:id => user.id) ,class: 'btn btn-default'%></td>       
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.role == 'Admin'%>
  <%= link_to 'Final Candidates' ,final_candidate_candidates_path , :class => 'btn btn-default'%>
<%end%>

app/views/home/winner.html.erb
<h2>Winner Candidate</h2>
Name : <%= @candidate.name%></br>
Age : <%= @candidate.age%>