config/routes.rb
Rails.application.routes.draw do
  
  resources :vote_schedules
  get 'home/index'
  get 'home/activate_selector'
  get 'home/candidate'
  get 'home/final_candidate'
  get 'home/select_candidate'
  get 'home/winner'

  resources :candidates do
    collection do
      get 'final_candidate'
    end
  end
  devise_for :users
  root to: "home#index"

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  validates_uniqueness_of :name
  validates_presence_of :name, :age
  scope :final_candidate, -> { where(selection_status: true)}
  before_save :check_winner
  has_many :votes
  has_many :users, through: :votes

  def check_winner
    users = User.all
    users.each do |user|
      AppMailer.winner(user,candidate = self).deliver
    end
  end


end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def final_candidate
    Vote.final_candidate
    @candidates = Candidate.all.where(:selection_status => true)
  end

  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :age)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/final_candidate.html.erb
<h1>Listing Final Candidates</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.age %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Candidates</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.age %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @candidate.age %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>